import { test, expect } from '@playwright/test';

test('Admin can update identity and generate report for export', async ({ page }) => {
  await page.goto('/');

  // Login as Admin
  await page.locator('button:has-text("Administrator")').click();
  await page.fill('input[placeholder="Username"]', 'admin');
  await page.fill('input[placeholder="Password"]', 'password123');
  await page.click('button:has-text("Sign In")');

  // Navigate to Settings
  await page.click('text=Settings');
  await page.waitForSelector('text=Company Identity');

  // Update company name
  const newName = 'TestCorp E2E';
  await page.locator('input').first().fill(newName);
  await page.click('button:has-text("Save Identity")');

  // Wait for save confirmation
  await expect(page.locator('button:has-text("Saved")')).toBeVisible();

  // Go to Team and open first member
  await page.click('text=Team');
  await page.waitForSelector('text=Details');
  await page.locator('a:has-text("Details")').first().click();

  // Open Report tab
  await page.click('button:has-text("Report")');

  // Generate a local report and verify print content
  await page.click('button:has-text("Generate Report")');

  // The print content exists in DOM even if hidden; check it contains the company name
  const reportText = await page.locator('#print-report-content').innerText();
  expect(reportText).toContain(newName);
  expect(reportText).toContain('End of Brief • Generated by PerformX');
});
